/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface PieChartDemo {}
  interface PieChartDemoAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'PieChartDemo': Components.PieChartDemo;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'pie-chart-demo': Components.PieChartDemoAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPieChartDemoElement extends Components.PieChartDemo, HTMLStencilElement {}
  var HTMLPieChartDemoElement: {
    prototype: HTMLPieChartDemoElement;
    new (): HTMLPieChartDemoElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'pie-chart-demo': HTMLPieChartDemoElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'pie-chart-demo': HTMLPieChartDemoElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
